export const images = {
  ic_plane : require('../assets/ph.png'),
  ph: require('../assets/ph.png'),
  ph2: require('../assets/ph_2.png'),
  l_3: require('../assets/l_3.jpeg'),
  ic_one_say_sign: require('../assets/ic_one_say_sign.png'),
  bell: require('../assets/bell.png'),
  plus: require('../assets/plus.png'),
  story: require('../assets/story.png'),
  home_ic: require('../assets/home.png'),
  call_ic: require('../assets/call.png'),
  chat_ic: require('../assets/chat.png'),
  user_ic: require('../assets/user.png'),
  app_logo: require('../assets/icon.png'),
  eye_show: require('../assets/show.png'),
  ic_add: require('../assets/ic_add.png'),
  ic_done: require('../assets/ic_done.png'),
  ic_cancel: require('../assets/ic_cancel.png'),
  avatar: require('../assets/avatar.png'),
  add_cat: require('../assets/add_cat.png'),
  reels_ic: require('../assets/reels.png'),
  menu_ic: require('../assets/menu_ic.png'),
  lock_ic: require('../assets/lock_ic.png'),
  more_ic: require('../assets/more_ic.png'),
  bg_gray: require('../assets/bg_gray.png'),
  back_white: require('../assets/back.png'),
  demo_img: require('../assets/demo_img.png'),
  heart_ic: require('../assets/heart_ic.png'),
  avatar_1: require('../assets/avatar_1.png'),
  avatar_2: require('../assets/avatar_2.png'),
  video_ic: require('../assets/video_ic.png'),
  settings: require('../assets/settings.png'),
  add_full: require('../assets/add_full.png'),
  terms_ic: require('../assets/terms_ic.png'),
  right_ic: require('../assets/right_ic.png'),
  new_chat: require('../assets/new_chat.png'),
  call_btn: require('../assets/call_btn.png'),
  chat_btn: require('../assets/chat_btn.png'),
  network_ic: require('../assets/network.png'),
  logout_ic: require('../assets/logout_ic.png'),
  search_ic: require('../assets/search_ic.png'),
  ic_camera: require('../assets/ic_camera.png'),
  new_group: require('../assets/new_group.png'),
  video_btn: require('../assets/video_btn.png'),
  volume_up: require('../assets/volume_up.png'),
  sound_off: require('../assets/sound_off.png'),
  dollar_ic: require('../assets/dollar_ic.png'),
  menu_line: require('../assets/menu_line.png'),
  back_black: require('../assets/back_black.png'),
  account_ic: require('../assets/account_ic.png'),
  report_acc: require('../assets/report_acc.png'),
  profilePic: require('../assets/profilePic.png'),
  plus_round: require('../assets/plus_round.png'),
  reel_heart: require('../assets/reel_heart.png'),
  balance_ic: require('../assets/balance_ic.png'),
  message_ic: require('../assets/message_ic.png'),
  plus_small: require('../assets/plus_small.png'),
  community_ic: require('../assets/community.png'),
  language_ic: require('../assets/language_ic.png'),
  new_contact: require('../assets/new_contact.png'),
  new_channel: require('../assets/new_channel.png'),
  dotted_line: require('../assets/dotted_line.png'),
  bookmark_ic: require('../assets/bookmark_ic.png'),
  subtract_ic: require('../assets/subtract_ic.png'),
  search_blue: require('../assets/search_blue.png'),
  bg_elevation: require('../assets/bg_elevation.png'),
  settings_acc: require('../assets/settings_acc.png'),
  address_book: require('../assets/address_book.png'),
  video_record: require('../assets/video_record.png'),
  coin_earn_ic: require('../assets/coin_earn_ic.png'),
  telephone_ic: require('../assets/telephone_ic.png'),
  welcome_menu: require('../assets/welcome_menu.png'),
  walkthrogh_1: require('../assets/walkthrogh_1.png'),
  walkthrogh_2: require('../assets/walkthrogh_2.png'),
  walkthrogh_3: require('../assets/walkthrogh_3.png'),
  walkthrogh_4: require('../assets/walkthrogh_4.png'),
  rightArrow_ic: require('../assets/rightArrow_ic.png'),
  call_message_ic: require('../assets/call_message.png'),
  setting_bar_ic: require('../assets/setting_bar_ic.png'),
  share_money_ic: require('../assets/share_money_ic.png'),
  bg_search_page: require('../assets/bg_search_page.png'),
  btnCallDecline: require('../assets/btnCallDecline.png'),
  iconDecline_3x: require('../assets/iconDecline_3x.png'),
  notification_ic: require('../assets/notification_ic.png'),
  preferences_acc: require('../assets/preferences_acc.png'),
  notication_blue: require('../assets/notication_blue.png'),
  icCall_Primary: require('../assets/icCallFilled_20.png'),
  up_volume: require('../assets/up_volume.png'),
  down_volume: require('../assets/down_volume.png'),
  doggy: require('../assets/doggy.png'),
  ic_flip_camera: require('../assets/ic_flip_camera.png'),

  qr_code: require('../assets/qr_code.png'),
  radio_fill: require('../assets/radio_fill.png'),
  radio_ring: require('../assets/radio_ring.png'),

  card_ic: require('../assets/card_ic.png'),
  market_place: require('../assets/m_place.png'),

  categories: require('../assets/categories.png'),
  share_link:require('../assets/share_link.png'),
  whatsapp:require('../assets/whatsapp.png'),
  email:require('../assets/email.png'),
  qr_code:require('../assets/qr_code.png'),
  sms:require('../assets/sms.png'),
  ic_share_qrCode :require('../assets/ic_share_qrcode.png'),
  copy_link :require('../assets/copy_link.png'),



};
