import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({

en: {

//MARK: Welcome Page:
SA_STR_WELCOME_SIGN_UP : 'Sign Up',
SA_STR_WELCOME_VERSION : "Version",

//MARK: Login Page:
login : 'Login',
signup : 'Sign Up',
SA_STR_EMAIL_USERNAME : 'Email or Username',
SA_STR_PASSWORD : 'Password',
SA_STR_Forgot_PASSWORD : 'Forgot Password?',

//MARK: Reset Password
SA_STR_RESET_PASSWORD_PLEASEWAIT : "Please wait",
SA_STR_RESET_PASSWORD_TOKEN : "We are sending you reset token.",
SA_STR_RESET_PASSWORD_VALID_EMAIL_MSG : "Please enter valid email",
SA_STR_RESET_PASSWORD_SUBMIT : "Submit",
SA_STR_RESET_PASSWORD_EMAIL : "Email",
SA_STR_RESET_PASSWORD_SUCCESS_MSG : "We’ve sent you an email to reset your password.",
SA_STR_RESET_PASSWORD_SUCCESS_SUB_MSG : "If you don’t receive an email within few minutes (check your spam too), please contact support@onesay.app",
SA_STR_RESET_PASSWORD_SUCCESS_LOGIN_MSG : "We’ve sent you an email to reset your password.",
SA_STR_RESET_PASSWORD_SUCCESS_ALERT_TITL : "OK, got it",
ResetPasswordTitle : "Reset your\nPassword",
ResetPasswordHeading : "Enter your email address. We’ll email you a token code that will allow you to reset your password.",

//MARK: Change Password
SA_STR_CHANGE_PASSWORD_SUCCESS_ALERT_TITLE : "Create new\nPassword",
SA_STR_CHANGE_PASSWORD_SUCCESS_MSG : "Password changed successfully",
SA_STR_CHANGE_PASSWORD_RESET_BUTTON : "Reset Password",
SA_STR_CHANGE_PASSWORD_TOKEN : "Token",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_8 : "Must Contain at least 8 characters (12 Recommended)",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_UPPER_CASE : "Must Contain at least one uppercase letter",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_LOWER_CASE  : "Must Contain at least one lowercase letter",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_SPECIALCHARACTER : "Must Contain at least one special character (!”#&’()+:/<:>?@[/])",
SA_STR_CHANGE_PASSWORD_RESETTING : "Resetting Password",


//MARK: Registration Page Exigo...
SA_STR_REGISTRTION_EXIGO_HEADING  : "Create an account with\nan existing username",
SA_STR_REGISTRTION_EXIGO_USERNAME : "Username",
SA_STR_REGISTRTION_EXIGO_PASSWORD : "Password",
SA_STR_REGISTRTION_EXIGO_REGISTER : "Register",
SA_STR_REGISTRTION_EXIGO_OR : "OR",
SA_STR_REGISTRTION_EXIGO_ACCEPT : "I accept the ",
SA_STR_REGISTRTION_EXIGO_TERMS : "Terms,",
SA_STR_REGISTRTION_EXIGO_PRIVACY : "Privacy",
SA_STR_REGISTRTION_EXIGO_AND : "and",
SA_STR_REGISTRTION_EXIGO_EULA : "EULA",

//MARK: Registration
SA_STR_REGISTRTION_FIRST_NAME : "First Name",
SA_STR_REGISTRTION_LAST_NAME : "Last Name",
SA_STR_REGISTRTION_DOB : "Date of birth",
SA_STR_REGISTRTION_GENDER : "Gender",
SA_STR_REGISTRTION_EMAIL : "Email",
SA_STR_REGISTRTION_USERNAME : "Username",
SA_STR_REGISTRTION_PASSWORD : "Password",
SA_STR_REGISTRTION_CONFIRM_PASSWORD : "Confirm Password",
SA_STR_REGISTRTION_PHONENUMBER : "Phone Number",
SA_STR_REGISTRTION_REFERRAL : "Referral Code",
SA_STR_REGISTRTION_NEW_ACCOUNT : "Register a new account",
SA_STR_REGISTRTION_SUBMIT : "Submit",
SA_STR_REGISTRTION_COUNTRY : "Country",

comments: 'Comments',
no_comment_found: 'No Comment Found',
post_comment: 'Post Comment',
Languages: 'Languages',
Language: 'Language',
ContactUs: 'Contact Us',
Change_Language: 'Change Language',
App_Language_Changed_to: 'The app language will be changed to',
OK: 'OK',
Cancel: 'Cancel',
Invite: 'Invite',
Edit_Profile: 'Edit Profile',
Terms_Of_Use: 'Terms Of Use',
Privacy_Policy: 'Privacy Policy',
Settings: 'Settings',
Delete_Account: 'Delete Account',
Logout: 'Logout',
Account_Verification: 'Account Verification',
Do_not_disturb: 'Do not disturb',
Snooze: 'Snooze',
Chats: 'Chats',
Font_size: 'Font size',
Show_last_seen: 'Show last seen',
Privacy: 'Privacy',
view_profile: 'View Profile',
membership_level: 'Membership Level',
sa_str_wallet: 'Wallet',
my_wallet: 'My Wallet',
update: 'Update',
manage: 'Manage',
see_your_benefits: 'SEE YOUR BENEFITS',
rank_ladder: 'Rank Ladder',
my_missions: 'My Missions',
buy_coins: 'Buy Coins',
add_friends: 'Add Friends',
market_place: 'Market Place',
contributors: 'Contributors',
invite_3_friends: 'Invite 3 friends',
and_earn_5: 'and earn 5',
cap_buzzmi: 'BUZZMI',
invite: 'INVITE',
no_caps_invite: 'Invite',
home: 'Home',
chat: 'Chat',
trip: 'Trip',
hub: 'Hub',
account: 'Account',
select_membership: 'Select Membership',
membership: 'Membership',
back: 'Back',
later: 'Later',
get_this_membership: 'Get this membership',
dismiss: 'Dismiss',
go_back: 'Go back',
notifications: 'Notifications',
sa_str_verify_number_1: 'Verify your\nMobile Number',
del_your_acc_will: 'Deleting your account will',
del_your_acc_info_and_profile_photo:
  'Delete your account info and profile photo',
del_you_from_all_ones_say_groups: 'Delete you from all One’s Say groups',
del_your_mess_hist:
  'Delete your messages history on this phone and your backups',
temp_inactive_your_acc_will: 'Temporary inactive your account will',
temp_inact_your_ones_say_acc:
  "Temporarily inactivate your One's Say account",
not_disp_your_prof_det_in_ones_say:
  "Not display your profile/contact details in One's Say",
mark_login_cred_as_invalid: 'Mark your current login credential as invalid',
allow_to_activate_the_same_acc:
  "Allow to activate the same account when you wish throght the 'Forgot password' option",
your_phone_number: 'Your phone number',
delete_my_account: 'Delete My Account',
inactive_my_account: 'Inactive My Account',
write_reason: 'Write your reason please',
please_des_problem: 'Please describe the problem in more detail',
what_is_your_reason_for_leaving: 'What is your primary reason for leaving?',
are_you_sure_want_to_delete_account:
  'Are you sure you want to delete your account? This will permanently erase your account',
delete_all_caps: 'DELETE',
select_reason: 'Select Reason',
inactive_account: 'Inactive Account',
are_you_sure_inactive_account:
  "Are you sure you want to inactive your account? Please note you have an inactivated account with same Email/Mobile number in One's Say, visit 'Forget Password' to activate the same account or use different details to create a new account",
inactive: 'InActive',
done: 'Done',
are_you_sure_logout: 'Are you sure want to logout?',
no: 'No',
yes: 'Yes',
english: 'English',
spanish: 'Spanish',
account_details: 'Account Details',
display_name: 'Display Name',
user_Id: 'User ID',
username: 'Username',
first_name: 'First Name',
last_name: 'Last Name',
meeting_price: 'Meeting Price',
meeting_duration: 'Meeting Duration',
referral_code: 'Referral code',
sponsor: 'Sponsor',
date_of_birth: 'Date of Birth',
choose_image: 'Choose image',
gender: 'Gender',
male: 'Male',
female: 'Female',
other: 'Other',
sponsor_id: 'Sponsor ID',
are_you_sure_you_want: 'Are you sure you want',
as_your_sponsor: 'as your sponsor',
okay: 'Okay',
invalid_referral_code: 'Invalid referral code',
please_enter_display_name: 'Please enter display name',
display_name_should_not:
  'Display name should not contain any numbers, should be one word and should be between 3 and 20 characters long.',
please_enter_first_name: 'Please enter first name',
please_enter_valid_first_name:
  'First name should not contain any numbers and should be between 3 and 20 characters long',
please_enter_last_name: 'Please enter last name',
please_enter_valid_last_name:
  'Last name should not contain any numbers and should be between 3 and 20 characters long.',
please_enter_dob: 'Please enter your birth date',
please_enter_valid_dob: 'Please enter valid birth date',
please_select_gender: 'Please specify your gender',
meeting_price_cannot: 'Meeting price cannot be 0',
take_photo: 'Take Photo',
verify_account: 'Verify Account',
mobile_number: 'Mobile Number',
email: 'Email',
verify: 'Verify',
two_factor_authentication: 'Two-factor authentication',
add_extra_layer:
  'Add an extra layer of security to your account by enabling two-factor authentication.',
please_enter_mobile_number: 'Please enter mobile number',
please_enter_valid_phone: 'Please enter a valid phone number',
please_enter_email: 'Please enter email',
please_enter_valid_email: 'Please enter valid email',
enter_your_verification_code: 'Enter your verification code',
we_sent_the_code: 'We sent the code to the',
phone_small: 'phone',
email_small: 'email',
this_code_will_expire: 'This code will expire in',
new_password: 'New Password',
confirm_password: 'Confirm Password',
submit: 'Submit',
resend_code: 'Resend code',
please_enter_received_code: 'Please enter the received code.',
please_enter_password: 'Please enter password',
invalid_password: 'Invalid Password',
please_enter_confirm_password: 'Please enter confirm password',
passwords_do_not_match: 'Passwords do not match',
password_length_to_be: '- Password Length to be 8 minimum and 15 maximum\n',
at_least_one_special_char: '- At least one Special Char\n',
at_least_one_capital_letter: '- At least one Capital Letter\n',
at_least_one_number: '- At least one Number\n',
no_more_than_two_consecutive: '- No more than two consecutive characters',
enable_now: 'Enable Now',
enable_twofactor_auth: 'Enable Two-factor authentication',
an_authenticator_app_lets_you:
  'An authenticator app lets you generate security codes on your phone without needing to receive text messages. If you don`t already have one, we support e. g. these apps.',
to_configure_your: 'To configure your authenticator app:',
add_a_new_timebased:
  'Add a new time-based token \nUse your app to scan the QR-code below',
enter_the_code_generated: 'Enter the code that was generated',
code: 'Code',
validate: 'Validate',
save: 'Save',
change: 'Change',
disable_now: 'Disable Now',
enable_successfully: 'enable successfully',
secret_key_copied: 'Secret key copied',
contributionscore: 'ContributionScore',
activity: 'Activity',
gained_score: 'Gained_score',
date_created: 'Date Created',
contributor_not_found: 'Contributor not found',
start_time: 'Start Time',
end_time: 'End Time',
this_option_routinely:
  'This option will routinely suspend notifications for set periods each day.',
please_select_start_time: 'Please select start time!',
please_select_end_time: 'Please select end time!',
start_time_end_time_not_same: 'Start time and end time cannot be same!',
please_select_valid_start_date: 'Please select a valid start date.',
search: 'Search',
feed: 'Feed',
reels: 'Reels',
myposts: 'MyPosts',
choose_photo: 'Choose photo',
confirm: 'Confirm',
select_date: 'Select date',
select_time: 'Select time',
edit: 'Edit',
delete: 'Delete',
tap_options: 'Tap options',
change_channel_image: 'Change channel image',
view: 'View',
choose_file: 'Choose File',
error_open_photo_lib: "Couldn't open photo library.",
error_open_camera: "Couldn't open camera.",
allow_permission: 'Allow permission',
cap_settings: 'SETTINGS',
error_upload_image: 'Could not upload the image.',
points: 'Points',
total: 'Total',
spent: 'Spent',
wallet_activity: 'Wallet Activity',
to: 'To',
no_activity_found: 'No activity found',
clear: 'Clear',
categories: 'Categories',
all_categories: 'All categories',
no_product_found: 'No product found',
store: 'Store',
all_offers: 'All Offers',
cash_back: 'Cash Back',
get_deal: 'Get deal',
error_only_edit_your_products: 'You can only edit your products',
delete_category: 'Delete Category',
warn_delete_category: 'Are you sure you want to delete this category?',
warn_no_vendor_account:
  "Seems like you don't have vendor account access. Do you want to initiate singup process?",
add_product: 'Add Product',
product_name: 'Product Name',
product_price: 'Product Price',
select_category: 'Select Category',
category_title: 'Category Title',
suspicious: 'Suspicious',
harassing: 'Harassing',
inappropriate: 'Inappropriate',
spam: 'Spam',
edit_category: 'Edit Category',
add_category: 'Add Category',
all: 'All',
group: 'Group',
channel: 'Channel',
contacts: 'Contacts',
network: 'Network',
missed: 'Missed',
call_history: 'Call History',
warn_no_record_found: 'No Record Found',
following: 'Following',
followers: 'Followers',
views: 'Views',
streamer_hours: 'Streamer hours',
follow: 'Follow',
mute: 'Mute',
search_message: 'Search Message',
block_contact: 'Block message',
report: 'Report',
report_type: 'Report type',
calling: 'Calling',
cancelled: 'Cancelled...',
cap_cancelled: 'CANCELLED...',
outgoing: 'Outgoing',
incoming: 'Incoming',
new_chat: 'New Chat',
new_group: 'New group',
new_contact: 'New contact',
new_channel: 'New channel',
unblock_contact: 'Unblock Contact',
message: 'Message',
warn_write_your_reason: 'Write your reason please',
got_it: 'Got it',
user_reported: 'User Reported',
warn_report_noted: 'Your report is noted. we will review this',
warn_select_reason: 'Please select the reason',
channel_reported: 'Channel Reported',
group_reported: 'Group Reported',
sa_str_end_to_end_encrypted:
  'Messages and calls are end-to-end encrypted.\nNo one outside this chat, not even Buzzmi,\ncan read or listen to them.',
channel_is_frozen: 'Channel is frozen',
sa_str_last_seen: 'Last seen',
sa_str_last_seen_yesterday: 'Last seen yesterday',
sa_str_group_yesterday: 'Yesterday',
last_seen_a_week_ago: 'Last seen 1 week ago',
last_seen_few_week_ago: 'Last seen few weeks ago',
warn_user_is_on_dnd: 'This user is currently on do not disturb mode.',
warn_user_is_on_snooze: 'This user is currently on snooze mode.',
Insufficient_permissions: 'Insufficient permissions!',
warn_allow_camera_and_microphone_access:
  'To call, allow Buzzmi access to your camera and microphone',
failed: 'Failed',
online: 'Online',
is_now_an_admin: 'is now an admin.',
msg_channel_created: 'The channel is created.',
msg_group_created: 'The group is created.',
and: 'and',
joined_dot: 'joined.',
chat_is_unavailable: 'Chat is unavailable',
write_a_message: 'Write a message',
error_sending_message: "Couldn't send message.",
msg_no_longer_admin: 'is no longer an admin.',
error_opening_files: "Couldn't open files.",
error_receiver_blocked:
  'Receiver is blocked. Unblock the user to send message',
slide_to_cancel: 'Slide to cancel',
camera: 'Camera',
photo_library: 'Photo library',
warn_need_mic_permission: 'Need microphone permission to proceed!',
retry: 'Retry',
remove: 'Eliminar',
delete_message: 'Delete Message?',
error_delete_message: "Couldn't delete message.",
copy: 'Copy',
copied: 'Copied',
read_by: 'Read by',
delivered_to: 'Delivered to',
downloading: 'Downloading...',
file_saved: 'File saved',
error_download_file: "Couldn't download file.",
files: 'Files',
error_cam_not_available: 'Camera not available',
photo: 'Photo',
one_week_ago: '1 week ago',
few_weeks_ago: 'few weeks ago',
you: 'You',
turn_off_notifications: 'Turn off notifications',
turn_on_notifications: 'Turn on notifications',
error_turning_on_notifications: "Couldn't turn on notifications.",
error_turning_off_notifications: "Couldn't turn off notifications.",
warn_sure_delete: 'Are you sure you want to delete?',
error_leave_channel: "Couldn't leave channel.",
leave_channel: 'Leave channel',
members: 'Members',
add_members: 'Add Members',
invite_members: 'Invite Members',
operators: 'Operators',
operator: 'Operator',
banned_members: 'Banned Members',
muted_members: 'Muted Members',
reported_members: 'Reported Members',
report_channel: 'Report Channel',
report_group: 'Report Group',
freeze_channel: 'Freeze Channel',
leave_group: 'Leave Group',
admins: 'Admins',
need_camera_permission: 'Need camera permission to proceed!',
demote: 'Demote',
are_you_sure_dismiss_memeber:
  'Are you sure you want to dismiss this member as a',
no_name: 'No Name',
dismiss_from: 'Dismiss From',
owner: 'Owner',
ban: 'Ban',
are_you_sure_to_ban: 'Are you sure you want to ban this member?',
unmute: 'Unmute',
are_you_sure_want_unmute: 'Are you sure you want to Unmute this member?',
are_you_sure_want_mute: 'Are you sure you want to mute this member?',
dismiss_from_operator: 'Dismiss From Operator',
promote_operator: 'Promote Operator',
report_member: 'Report member',
are_you_sure_want_report: 'Are you sure you want to report?',
remove_from: 'Remove From',
remove_from_admin: 'Remove From Admin',
make_admin: 'Make Admin',
admin: 'Admin',
next: 'Next',
invite_user: 'Invite User',
are_not_memeber_of_onesay:
  " are not memeber of one'say. Do you want to send invitation to them?",
please_select_users: 'Please select users',
create_channel: 'Create channel',
create_group: 'Create group',
create: 'Create',
please_enter_channel_name: 'Please enter channel name',
please_enter_group_name: 'Please enter group name',
post: 'Post',
reel: 'Reel',
create_post: 'Create Post',
whats_on_your_mind: "What's on your mind",
upload: 'Upload',
reels_updated_successfully: 'Reels updated Successfully',
please_enter_content: 'Please enter content',
reels_added_successfully: 'Reels added Successfully',
error_while_uploading_reels: 'Error while uploading reels',
content_should_be_at_least: 'Content should be at least 3 character',
couldnt_reach_server:
  "Couldn't reach server. Check your internet connection",
to_call_allow_buzzmi_access:
  'To call, allow Buzzmi access to your camera and microphone',
to_answer_allow_buzzmi_access:
  'To answer, allow Buzzmi access to your camera and microphone',
you_need_grant_storage_access:
  'You need to grant storage access permissions.',
permissions_for_record_audio: 'Permissions for record audio',
give_permission_record_audio:
  'Give permission to your device to record audio',
You_need_grant_microphone:
  'You need to grant microphone access permissions.',
send: 'Send',
left_leave: 'left.',
send_invitation: 'Send Invitation',
mobile: 'Mobile',
invitation_sent_success: 'Invitation send successfully',
add_a_contact: 'Add a contact',
to_a_channel: 'to a channel',
add: 'Add',
warn_invitation_link_sent: 'Invitation link send successfully',
invite_to_channel_via_link: 'Invite to channel via link',
invite_with_link_description:
  'Anyone with Buzzmi can follow this link to join this channel. Only share it with people you trust',
send_link_via_buzzmi: 'Send link via Buzzmi',
link_copied_with_success: 'Invitation link copied successfully',
copy_link: 'Copy link',
banned: 'Banned',
msg_sure_to_un_ban: 'Are you sure you want to unbanned this member?',
msg_sure_to_un_mute: 'Are you sure you want to unmute this member?',
warn_no_banned_users: 'No Banned User Found',
warn_no_mute_users: 'No Mute User Found',
warn_no_reported_users: 'No Reported Member Found',
msg_report_group:
  'The last 5 messages from this group will be forwarded to Buzzmi. If you exit this group and delete the chat, message will only be removed from the device and your devices on the newer version of Buzzmi.',
msg_report_channel:
  'The last 5 messages from this channel will be forwarded to Buzzmi. If you exit this channel and delete the chat, message will only be removed from the device and your devices on the newer version of Buzzmi.',
report_this: 'Report this',
no_one_in_the: 'No one in the',
will_be_notified: 'will be notified',
exit_something: 'Exit',
and_delete_chat: 'and delete chat',
change_channel_name: 'Change channel name',
change_group_name: 'Change group name',
enter_name: 'Enter name',
change_group_image: 'Change group image',
channel_information: 'Channel information',
no_travel_packages_available: 'No travel packages available',
no_slots_available_for_date: 'No slots available for this date!',
unable_to_get_user_availability: 'Unable to get user availability',
please_enter_details: 'Please enter details',
reel_downvoted_successfully: 'Reel downvoted successfully',
reel_upvoted_successfully: 'Reel upvoted successfully',
delete_reel: 'Delete Reel',
delete_post: 'Delete Post',
are_you_sure_delete_this_reel: 'Are you sure you want to delete this reel?',
are_you_sure_delete_this_post: 'Are you sure you want to delete this post?',
buzzmi_need_permission_to_access_your_device_storage:
  'Buzzmi need permission to access your device storage. Go to Settings to allow access',
trending: 'Trending',
tweets: 'tweets',
post_update_success: 'Post updated successfully',
edit_post: 'Edit Post',
post_added_success: 'Post added successfully',
report_description: 'Report description',
report_by: 'Report By',
report_details: 'Report Details',
msg_you_can_add: (id, type) =>
  `You can add ${id} to help you for manage your ${type}. Press and hold to remove them. `,
limit_not_reached: 'Limit Not Reached',
voice_note_min_limit_2_sec: 'Voice note must be at least 2 seconds.',
receiver_is_blocked:
  'Receiver is blocked. \n Unblocked the user to send message',
alert_permissions_message: (permission, appName) =>
  `${appName} need permission to access your ${permission}. Go to Settings to allow access`,
the_channels_image_was_updated: "The channel's image was updated.",
the_groups_image_was_updated: "The group's image was updated.",
edited: '(edited)',
promote: 'promote',
msg_are_you_sure_admin: (status, id) =>
  `Are you sure you want to ${status} this member as a ${id}`,
added_success: 'added successfully.',
at: 'at',
msg_what_can_this_do: id => `What can this ${id} do?`,
rights: 'Rights',
change_channel_info: 'Change channel info',
add_remove_members: 'Add/Remove Members',
invite_users_via_link: 'Invite Users via Link',
add_or_remove: 'Add/Remove',
ban_members: 'Ban Members',
mute_members: 'Mute Members',
report_members: 'Report Members',
delete_account: 'Delete Account',
deleting_your_account_will: 'Deleting your account will',
delete_your_account_profile: 'Delete your account info and profile photo',
delete_from_buzzmi_groups: 'Delete you from all Buzzmi groups',
delete_messages_and_backup:
  'Delete your messages history on this phone and your backups',
temp_inactive_your_account: 'Temporary inactive your account will',
your_buzzmi_acc_temp_inactive:
  'Temporarily inactivated your Buzzmi account',
not_display_buzzmi_profile:
  'Not display your profile/contact details in Buzzmi',
make_login_invalid: 'Mark your current login credential as invalid',
allow_acc_active_with_forgot_pass:
  "Allow to activate the same account when you wish through the 'Forgot password' option",
del_my_acc: 'Delete My Account',
inactive_my_acc: 'Inactive My Account',
msg_inactive_acc_confirm:
  "Are you sure you want to inactive your account? Please note you have an inactivated account with same Email/Mobile number in Buzzmi, visit 'Forget Password' to activate the same account or use different details to create a new account",
currency: 'Currency',
awarded_on: 'Awarded On',
award_type: 'Awarded Type',
share_link: 'Share Link',
qr_code: 'QR Code',
share_file: 'Share file',
is_muted: 'is muted',
voice: 'voice',
call: 'call',
completed: 'COMPLETED',
missed_call: 'Missed Call',
},
es: {
//MARK: Welcome Page
SA_STR_WELCOME_SIGN_UP : 'Inscribirse',
SA_STR_WELCOME_VERSION : "Versión",

//Mark: Login page:
SA_STR_EMAIL_USERNAME : "Correo electrónico o nombre de usuario",
SA_STR_PASSWORD : "Clave",
SA_STR_Forgot_PASSWORD : "¿Has olvidado tu contraseña?",
login: 'Acceso',

//MARK: Reset Password
SA_STR_RESET_PASSWORD_PLEASEWAIT : "Espere por favor",
SA_STR_RESET_PASSWORD_TOKEN : "Le estamos enviando token de restablecimiento.",
SA_STR_RESET_PASSWORD_VALID_EMAIL_MSG : "Por favor introduzca un correo electrónico válido",
SA_STR_RESET_PASSWORD_SUBMIT : "Enviar",
SA_STR_RESET_PASSWORD_EMAIL : "Envidiar",
SA_STR_RESET_PASSWORD_SUCCESS_MSG : "Le hemos enviado un correo electrónico para restablecer su contraseña.",
SA_STR_RESET_PASSWORD_SUCCESS_SUB_MSG : "Si no recibe un correo electrónico en unos minutos (consulte su spam también), comuníquese con support@onesay.app",
SA_STR_RESET_PASSWORD_SUCCESS_LOGIN_MSG : "Le hemos enviado un correo electrónico para restablecer su contraseña.",
SA_STR_RESET_PASSWORD_SUCCESS_ALERT_TITL : "Ok lo tengo",
ResetPasswordTitle : "Reinicia tu\nClave",
ResetPasswordHeading : "Ingrese su dirección de correo electrónico. Le enviaremos un correo electrónico con un código de token que le permitirá restablecer su contraseña.",

//MARK: Change Password
SA_STR_CHANGE_PASSWORD_SUCCESS_ALERT_TITLE  : "Crear nueva\ncontraseña",
SA_STR_CHANGE_PASSWORD_SUCCESS_MSG : "Contraseña cambiada con éxito",
SA_STR_CHANGE_PASSWORD_RESET_BUTTON : "Restablecer la contraseña",
SA_STR_CHANGE_PASSWORD_TOKEN : "Simbólico",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_8 : "Debe contener al menos 8 caracteres (12 recomendados)",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_UPPER_CASE : "Debe contener al menos una letra mayúscula",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_LOWER_CASE  : "Debe contener al menos una letra minúscula",
SA_STR_CHANGE_PASSWORD_MUST_CONTAINS_AT_LEAST_1_SPECIALCHARACTER : "Debe contener al menos un personaje especial (!#&()+:<:>?@[])''" ,
SA_STR_CHANGE_PASSWORD_RESETTING : "Restablecimiento de contraseña",
SA_STR_ALERT_ALL_FIELDS : "Por favor llene todos los campos",
SA_STR_ALERT_LICENCS : "Acepte los términos y la condición",
SA_STR_ALERT_PASSWRDMATCH : "Contraseña y confirmar la contraseña debe coincidir",
SA_STR_ALERT_SIGNUP : "Registrarse",

//MARK: Exigo Registration...
SA_STR_REGISTRTION_EXIGO_HEADING  : "Crear una cuenta con un nombre de usuario existente",
SA_STR_REGISTRTION_EXIGO_USERNAME : "Nombre de usuario",
SA_STR_REGISTRTION_EXIGO_PASSWORD : "Clave",
SA_STR_REGISTRTION_EXIGO_REGISTER : "Registro",
SA_STR_REGISTRTION_EXIGO_OR : "O",
SA_STR_REGISTRTION_EXIGO_ACCEPT : "Acepto el ",
SA_STR_REGISTRTION_EXIGO_TERMS : "Términos,",
SA_STR_REGISTRTION_EXIGO_PRIVACY : "Privacidd",
SA_STR_REGISTRTION_EXIGO_AND : "y",
SA_STR_REGISTRTION_EXIGO_EULA : "EULA",

//MARK: Registration
SA_STR_REGISTRTION_FIRST_NAME : "Primer nombre",
SA_STR_REGISTRTION_LAST_NAME : "Apellido",
SA_STR_REGISTRTION_DOB : "Fecha de nacimiento",
SA_STR_REGISTRTION_GENDER : "Género",
SA_STR_REGISTRTION_EMAIL : "Correo electrónico",
SA_STR_REGISTRTION_USERNAME : "Nombre de usuario",
SA_STR_REGISTRTION_PASSWORD : "Clave",
SA_STR_REGISTRTION_CONFIRM_PASSWORD : "Confirmar contraseña",
SA_STR_REGISTRTION_PHONENUMBER : "Número de teléfono",
SA_STR_REGISTRTION_REFERRAL : "código de referencia",
SA_STR_REGISTRTION_NEW_ACCOUNT : "Registre una nueva cuenta",
SA_STR_REGISTRTION_SUBMIT : "Enviar",
SA_STR_REGISTRTION_COUNTRY : "País",

missed_call: 'Llamada perdida',
completed: 'TERMINADO',
call: 'llamar',
voice: 'voz',
is_muted: 'Está silenciado',
share_file: 'Recurso compartido de archivos',
qr_code: 'Código QR',
share_link: 'Compartir enlace',
award_type: 'Tipo adjudicado',
awarded_on: 'Otorgado el',
currency: 'Divisa',
msg_inactive_acc_confirm:
  "¿Está seguro de que desea inactivar su cuenta? Tenga en cuenta que tiene una cuenta inactiva con el mismo correo electrónico/número de teléfono móvil en Buzzmi, visite 'Olvidé mi contraseña' para activar la misma cuenta o use diferentes detalles para crear una nueva cuenta",
inactive_my_acc: 'Mi cuenta inactiva',
del_my_acc: 'Borrar mi cuenta',
allow_acc_active_with_forgot_pass:
  "Permita activar la misma cuenta cuando lo desee a través de la opción 'Olvidé mi contraseña'",
make_login_invalid:
  'Marque su credencial de inicio de sesión actual como no válida',
not_display_buzzmi_profile:
  'No mostrar tu perfil/detalles de contacto en Buzzmi',
your_buzzmi_acc_temp_inactive:
  'Desactivé temporalmente su cuenta de Buzzmi',
temp_inactive_your_account: 'Temporalmente inactiva su cuenta será',
delete_messages_and_backup:
  'Elimina tu historial de mensajes en este teléfono y tus copias de seguridad',
delete_from_buzzmi_groups: 'Eliminarte de todos los grupos de Buzzmi',
delete_your_account_profile:
  'Eliminar la información de su cuenta y la foto de perfil',
deleting_your_account_will: 'Eliminar su cuenta',
delete_account: 'Borrar cuenta',
report_members: 'Reportar miembros',
mute_members: 'Miembros mudos',
ban_members: 'Prohibir Miembros',
add_or_remove: 'Agregar/Eliminar',
invite_users_via_link: 'Invitar usuarios a través de un enlace',
add_remove_members: 'Agregar/eliminar miembros',
change_channel_info: 'Cambiar información del canal',
rights: 'Derechos',
msg_what_can_this_do: id => `¿Qué puede hacer este ${id}?`,
at: 'en',
added_success: 'agregado exitosamente.',
msg_are_you_sure_admin: (status, id) =>
  `¿Está seguro de que desea ${status} a este miembro como ${id}`,
promote: 'promover',
edited: '(editado)',
the_groups_image_was_updated: 'La imagen del grupo fue actualizada.',
the_channels_image_was_updated: 'La imagen del canal fue actualizada.',
alert_permissions_message: (permission, appName) =>
  `${appName} necesita permiso para acceder a su ${permission}. Ve a Ajustes para permitir el acceso`,
receiver_is_blocked:
  'El receptor está bloqueado.\n Desbloqueado el usuario para enviar mensaje',
voice_note_min_limit_2_sec:
  'La nota de voz debe ser de al menos 2 segundos.',
limit_not_reached: 'Límite no alcanzado',
msg_you_can_add: (id, type) =>
  `Puede agregar ${id} para ayudarlo a administrar su ${type}. Mantenga presionado para eliminarlos. `,
report_details: 'Detalles del informe',
report_by: 'Informe por',
report_description: 'Descripción del reporte',
post_added_success: 'Post added successfully',
edit_post: 'Edit Post',
post_update_success: 'Post updated successfully',
userListOperatorMessage:
  'You can add operator to help you for manage your channel. Press and hold to remove them.',
userListGroupMessage:
  'You can add admin to help you for manage your group. Press and hold to remove them.',
no_slots_available_for_date: 'No slots available for this date!',
unable_to_get_user_availability: 'unable to get user availability',
please_enter_details: 'Please enter details',
reel_downvoted_successfully: 'Reel downvoted successfully',
reel_upvoted_successfully: 'Reel upvoted successfully',
delete_reel: 'Delete Reel',
delete_post: 'Delete Post',
are_you_sure_delete_this_reel: 'Are you sure you want to delete this reel?',
are_you_sure_delete_this_post: 'Are you sure you want to delete this post?',
buzzmi_need_permission_to_access_your_device_storage:
  'Buzzmi need permission to access your device storage. Go to Settings to allow access',
trending: 'Trending',
tweets: 'tweets',

report_type: 'Tipo de informe',
sa_str_last_seen_yesterday: 'Visto por última vez ayer',
no_travel_packages_available: 'No hay paquetes de viaje disponibles',
channel_information: 'información del canal',
change_group_image: 'Cambiar imagen de grupo',
enter_name: 'Ingrese su nombre',
change_group_name: 'Cambiar nombre de grupo',
change_channel_name: 'Cambiar el nombre del canal',
and_delete_chat: 'y eliminar el chat',
exit_something: 'Salir del',
will_be_notified: 'será notificado',
no_one_in_the: 'Nadie en el',
report_this: 'Reporta esto',
msg_report_channel:
  'Los últimos 5 mensajes de este canal se reenviarán a Buzzmi. Si sale de este canal y elimina el chat, el mensaje solo se eliminará del dispositivo y de sus dispositivos en la versión más reciente de Buzzmi.',
msg_report_group:
  'Los últimos 5 mensajes de este grupo se reenviarán a Buzzmi. Si sale de este grupo y elimina el chat, el mensaje solo se eliminará del dispositivo y de sus dispositivos en la versión más reciente de Buzzmi.',
warn_no_reported_users: 'No se ha encontrado ningún miembro reportado',
warn_no_mute_users: 'No se encontró ningún usuario mudo',
warn_no_banned_users: 'No se ha encontrado ningún usuario prohibido',
msg_sure_to_un_mute:
  '¿Estás seguro de que quieres dejar de silenciar a este miembro?',
msg_sure_to_un_ban:
  '¿Estás seguro de que quieres desbanear a este miembro?',
banned: 'Prohibido',
copy_link: 'Copiar link',
link_copied_with_success: 'Enlace de invitación copiado con éxito',
send_link_via_buzzmi: 'Enviar enlace a través de Buzzmi',
invite_with_link_description:
  'Cualquier persona con Buzzmi puede seguir este enlace para unirse a este canal. Solo compártelo con personas en las que confíes.',
invite_to_channel_via_link: 'Invitar al canal a través de un enlace',
warn_invitation_link_sent: 'Enlace de invitación enviado con éxito',
add: 'Agregar',
to_a_channel: 'a un canal',
add_a_contact: 'Añade un contacto',
invitation_sent_success: 'Invitación enviada con éxito',
mobile: 'Móvil',
send_invitation: 'Enviar Invitacion',
send: 'Enviar',
comments: 'Comentarios',
no_comment_found: 'Ningún comentario encontrado',
post_comment: 'publicar comentario',
admins: 'Administradores',
leave_group: 'Abandonar grupo',
report_group: 'Grupo de informes',
add_members: 'Añadir miembros',
operator: 'Operador',
operators: 'Operadores',
banned_members: 'Miembros prohibidos',
muted_members: 'Miembros silenciados',
reported_members: 'Miembros Reportados',
report_channel: 'Canal de denuncia',
freeze_channel: 'Congelar canal',
members: 'Miembros',
leave_channel: 'Abandonar canal',
error_leave_channel: 'No podía salir del canal.',
warn_sure_delete: '¿Estás seguro de que quieres eliminar?',
error_turning_off_notifications:
  'No se pudieron desactivar las notificaciones.',
error_turning_on_notifications:
  'No se pudieron activar las notificaciones.',
turn_off_notifications: 'Desactivar las notificaciones',
turn_on_notifications: 'Activar las notificaciones',
you: 'Tú',
few_weeks_ago: 'hace algunas semanas',
one_week_ago: 'Hace 1 semana',
photo: 'Foto',
error_cam_not_available: 'Cámara no disponible',
files: 'archivos',
error_download_file: 'No se pudo descargar el archivo.',
file_saved: 'Archivo guardado',
downloading: 'Descargando...',
delivered_to: 'Entregado a',
read_by: 'Leído por',
copied: 'Copiado',
copy: 'Copiar',
error_delete_message: 'No se pudo eliminar el mensaje.',
delete_message: '¿Borrar mensaje?',
remove: 'Remove',
retry: 'Rever',
warn_need_mic_permission: '¡Necesita permiso del micrófono para continuar!',
photo_library: 'Librería fotográfica',
camera: 'Cámara',
slide_to_cancel: 'Deslizar para cancelar',
error_receiver_blocked:
  'El receptor está bloqueado. Desbloquear al usuario para enviar mensaje',
error_opening_files: 'No se pudieron abrir los archivos.',
msg_no_longer_admin: 'ya no es un administrador.',
error_sending_message: 'No se pudo enviar el mensaje.',
write_a_message: 'Escribe un mensaje',
chat_is_unavailable: 'El chat no está disponible',
msg_group_created: 'Se crea el grupo.',
and: 'y',
joined_dot: 'unido.',
is_now_an_admin: 'ahora es un administrador.',
msg_channel_created: 'Se crea el canal.',
online: 'En línea',
failed: 'Fallido',
warn_allow_camera_and_microphone_access:
  'Para llamar, permita que Buzzmi acceda a su cámara y micrófono',
Insufficient_permissions: '¡Permisos insuficientes!',
warn_user_is_on_snooze:
  'Este usuario está actualmente en modo de repetición.',
warn_user_is_on_dnd: 'Este usuario está actualmente en modo no molestar.',
last_seen_few_week_ago: 'Visto por última vez hace unas semanas',
last_seen_a_week_ago: 'Visto por última vez hace 1 semana',
sa_str_group_yesterday: 'Ayer',
sa_str_last_seen: 'Ultima vez visto',
channel_is_frozen: 'el canal esta congelado',
sa_str_end_to_end_encrypted:
  'Los mensajes y las llamadas están encriptados de extremo a extremo. Nadie fuera de este chat, \nni siquiera Buzzmi, puede leerlos o escucharlos.',
group_reported: 'Grupo Reportado',
channel_reported: 'Canal Reportado',
warn_select_reason: 'Por favor seleccione el motivo',
user_reported: 'Usuario reportado',
warn_report_noted: 'Se toma nota de su informe. revisaremos esto',
got_it: 'Entiendo',
warn_write_your_reason: 'Escribe tu razón por favor',
message: 'Mensaje',
unblock_contact: 'Desbloquear contacto',
new_contact: 'Nuevo contacto',
new_channel: 'Nuevo canal',
new_group: 'Nuevo grupo',
new_chat: 'Nueva conversación',
incoming: 'Llamada entrante',
outgoing: 'Llamada saliente',
following: 'Siguiente',
followers: 'Seguidores',
views: 'Puntos de vista',
streamer_hours: 'Horas de transmisión',
follow: 'Seguir',
mute: 'Mudo',
search_message: 'Mensaje de búsqueda',
block_contact: 'Bloquear mensaje',
report: 'Informe',
calling: 'Vocación',
left_leave: 'dejado.',
cancelled: 'Cancelado...',
cap_cancelled: 'CANCELADO...',
warn_no_record_found: 'Ningún record fue encontrado',
call_history: 'Historial de llamadas',
missed: 'Omitido',
network: 'Red',
contacts: 'Contactos',
all: 'Todo',
group: 'Grupo',
channel: 'Canal',
Languages: 'Idiomas',
Language: 'Idioma',
ContactUs: 'Contáctenos',
Change_Language: 'Cambiar idioma',
App_Language_Changed_to: 'El idioma de la aplicación cambiará a',
OK: 'DE ACUERDO',
Cancel: 'Cancelar',
Invite: 'Invitar',
Edit_Profile: 'Editar perfil',
Terms_Of_Use: 'Condiciones de uso',
Privacy_Policy: 'política de privacidad',
Settings: 'Ajustes',
Delete_Account: 'Borrar cuenta',
Logout: 'Cerrar sesión',
Account_Verification: 'Verificación de la cuenta',
Do_not_disturb: 'No molestar',
Snooze: 'Siesta',
Chats: 'charlas',
Font_size: 'Tamaño de fuente',
Show_last_seen: 'Mostrar visto por última vez',
Privacy: 'Privacidad',
view_profile: 'Ver perfil',
membership_level: 'nivel de membresía',
sa_str_wallet: 'Cartera',
my_wallet: 'Mi billetera',
update: 'Actualizar',
manage: 'Administrar',
see_your_benefits: 'VEA SUS BENEFICIOS',
rank_ladder: 'Escala de rango',
my_missions: 'mis misiones',
buy_coins: 'Comprar monedas',
add_friends: 'Añade amigos',
market_place: 'mercado',
contributors: 'Colaboradores',
invite_3_friends: 'Invita a 3 amigos',
and_earn_5: 'y gana 5',
cap_buzzmi: 'BUZZMI',
invite: 'INVITAR',
no_caps_invite: 'Invitar',
home: 'Hogar',
chat: 'Charlar',
trip: 'Viaje',
hub: 'Centro',
account: 'Cuenta',
select_membership: 'Seleccione Membresía',
membership: 'Afiliación',
back: 'Atrás',
later: 'Más tarde',
get_this_membership: 'Obtén esta membresía',
dismiss: 'Despedir',
go_back: 'Regresa',
notifications: 'Notificaciones',
sa_str_verify_number_1: 'Verifique su \nnúmero de móvil',
del_your_acc_will: 'Eliminar su cuenta',
del_your_acc_info_and_profile_photo:
  'Eliminar la información de su cuenta y la foto de perfil',
del_you_from_all_ones_say_groups:
  "Eliminarte de todos los grupos de One's Say",
del_your_mess_hist:
  'Elimina tu historial de mensajes en este teléfono y tus copias de seguridad',
temp_inactive_your_acc_will: 'Temporalmente inactiva su cuenta será',
temp_inact_your_ones_say_acc:
  "Desactive temporalmente su cuenta de One's Say",
not_disp_your_prof_det_in_ones_say:
  "No mostrar su perfil/detalles de contacto en One's Say",
mark_login_cred_as_invalid:
  'Marque su credencial de inicio de sesión actual como no válida',
allow_to_activate_the_same_acc:
  "Permita activar la misma cuenta cuando lo desee a través de la opción 'Olvidé mi contraseña'",
your_phone_number: 'Su número de teléfono',
delete_my_account: 'Borrar mi cuenta',
inactive_my_account: 'Mi cuenta inactiva',
write_reason: 'Escribe tu razón por favor',
please_des_problem: 'Por favor, describa el problema con más detalle.',
what_is_your_reason_for_leaving: '¿Cuál es su razón principal para irse?',
are_you_sure_want_to_delete_account:
  '¿Está seguro de que desea eliminar su cuenta? Esto borrará permanentemente tu cuenta.',
delete_all_caps: 'BORRAR',
select_reason: 'Seleccionar motivo',
inactive_account: 'Cuenta inactiva',
are_you_sure_inactive_account:
  "¿Está seguro de que desea inactivar su cuenta? Tenga en cuenta que tiene una cuenta inactiva con el mismo correo electrónico/número de teléfono móvil en One's Say, visite 'Olvidé mi contraseña' para activar la misma cuenta o use detalles diferentes para crear una nueva cuenta",
inactive: 'Inactiva',
done: 'Hecho',
are_you_sure_logout: '¿Estás seguro de que quieres cerrar sesión?',
no: 'No',
yes: 'Sí',
english: 'Inglés',
spanish: 'Español',
account_details: 'detalles de la cuenta',
display_name: 'Nombre para mostrar',
user_Id: 'ID de usuario',
username: 'Nombre de usuario',
first_name: 'Nombre de pila',
last_name: 'Apellido',
meeting_price: 'Precio de reunión',
meeting_duration: 'Duración de la reunión',
referral_code: 'Código de referencia',
sponsor: 'Patrocinador',
date_of_birth: 'Fecha de nacimiento',
gender: 'Género',
choose_image: 'Elegir imagen',
male: 'Masculino',
female: 'femenina',
other: 'otro',
sponsor_id: 'Documento de identidad del patrocinador',
are_you_sure_you_want: 'Estas seguro que quieres',
as_your_sponsor: 'como tu patrocinador',
okay: 'Bueno',
invalid_referral_code: 'Código de referencia no válido',
please_enter_display_name: 'Ingrese el nombre para mostrar',
display_name_should_not:
  'El nombre para mostrar no debe contener números, debe ser una palabra y debe tener entre 3 y 20 caracteres.',
please_enter_first_name: 'Por favor, introduzca el nombre',
please_enter_valid_first_name:
  'El nombre no debe contener números y debe tener entre 3 y 20 caracteres',
please_enter_last_name: 'Por favor ingrese apellido',
please_enter_valid_last_name:
  'El apellido no debe contener números y debe tener entre 3 y 20 caracteres.',
please_enter_dob: 'Por favor, introduce tu fecha de nacimiento',
please_enter_valid_dob:
  'Por favor, introduzca una fecha de nacimiento válida',
please_select_gender: 'Por favor especifica tu género',
meeting_price_cannot: 'El precio de la reunión no puede ser 0',
verify_account: 'Verificar Cuenta',
take_photo: 'Tomar foto',
mobile_number: 'Número de teléfono móvil',
email: 'Correo electrónico',
two_factor_authentication: 'Autenticación de dos factores',
add_extra_layer:
  'Agregue una capa adicional de seguridad a su cuenta habilitando la autenticación de dos factores.',
please_enter_mobile_number: 'Por favor, introduzca el número de móvil',
please_enter_valid_phone: 'Por favor ingrese un número de teléfono válido',
please_enter_email: 'Por favor ingrese el correo electrónico',
please_enter_valid_email:
  'Por favor introduzca un correo electrónico válido',
enter_your_verification_code: 'Ingrese su código de verificación',
we_sent_the_code: 'Nosotros enviamos el codigo a',
phone_small: 'teléfono',
email_small: 'correo electrónico',
this_code_will_expire: 'Este código caducará en',
new_password: 'Nueva contraseña',
confirm_password: 'confirmar Contraseña',
submit: 'Entregar',
resend_code: 'Reenviar codigo',
please_enter_received_code: 'Por favor, introduzca el código recibido.',
please_enter_password: 'Por favor, ingrese contraseña',
invalid_password: 'Contraseña invalida',
please_enter_confirm_password: 'Por favor ingrese confirmar contraseña',
passwords_do_not_match: 'Las contraseñas no coinciden',
password_length_to_be:
  '- La longitud de la contraseña debe ser 8 mínimo y 15 máximo\n',
at_least_one_special_char: '- Al menos un personaje especial\n',
at_least_one_capital_letter: '- Al menos una mayúscula\n',
at_least_one_number: '- Al menos un Número\n',
no_more_than_two_consecutive: '- No más de dos caracteres consecutivos',
enable_twofactor_auth: 'Habilitar la autenticación de dos factores',
an_authenticator_app_lets_you:
  'Una aplicación de autenticación le permite generar códigos de seguridad en su teléfono sin necesidad de recibir mensajes de texto. Si aún no tiene uno, apoyamos e. gramo. estas aplicaciones.',
to_configure_your: 'Para configurar su aplicación de autenticación:',
add_a_new_timebased:
  'Agregar un nuevo token basado en el tiempo \nUse su aplicación para escanear el código QR a continuación',
enter_the_code_generated: 'Ingrese el código que se generó',
code: 'Código',
validate: 'Validar',
verify: 'Verificar',
enable_now: 'Habilitado ahora',
save: 'Ahorrar',
change: 'Cambiar',
disable_now: 'Deshabilitar ahora',
enable_successfully: 'habilitar con éxito',
secret_key_copied: 'Clave secreta copiada',
contributionscore: 'Puntuación de contribución',
activity: 'Actividad',
gained_score: 'Puntuación_ganada',
date_created: 'fecha de creacion',
contributor_not_found: 'Colaborador no encontrado',
start_time: 'Hora de inicio',
end_time: 'Hora de finalización',
this_option_routinely:
  'Esta opción suspenderá las notificaciones de forma rutinaria durante períodos establecidos cada día.',
please_select_start_time: '¡Seleccione la hora de inicio!',
please_select_end_time: '¡Seleccione la hora de finalización!',
start_time_end_time_not_same:
  '¡La hora de inicio y la hora de finalización no pueden ser iguales!',
please_select_valid_start_date: 'Seleccione una fecha de inicio válida.',
search: 'Buscar',
feed: 'Alimentar',
reels: 'Bobinas',
myposts: 'Mis publicaciones',
choose_photo: 'Escoge una foto',
confirm: 'Confirmar',
select_date: 'Seleccione fecha',
select_time: 'Seleccionar hora',
edit: 'Editar',
delete: 'Borrar',
tap_options: 'Toca opciones',
change_channel_image: 'Cambiar la imagen del canal',
view: 'Vista',
choose_file: 'Elija el archivo',
error_open_photo_lib: 'No se pudo abrir la biblioteca de fotos.',
error_open_camera: 'No se pudo abrir la cámara.',
allow_permission: 'Permitir permiso',
cap_settings: 'AJUSTES',
error_upload_image: 'No se pudo cargar la imagen.',
points: 'Puntos',
total: 'Total',
spent: 'gastado',
wallet_activity: 'Actividad de la billetera',
to: 'A',
no_activity_found: 'No se encontró actividad',
clear: 'Claro',
categories: 'Categorías',
all_categories: 'Todas las categorias',
no_product_found: 'No se encontró ningún producto',
store: 'Almacenar',
all_offers: 'Todas las ofertas',
cash_back: 'Devolución de dinero',
get_deal: 'Obtener oferta',
error_only_edit_your_products: 'Solo puedes editar tus productos',
delete_category: 'Eliminar categoría',
warn_delete_category: '¿Está seguro de que desea eliminar esta categoría?',
warn_no_vendor_account:
  'Parece que no tienes acceso a la cuenta de proveedor. ¿Quieres iniciar el proceso de registro?',
add_product: 'Agregar producto',
product_name: 'Nombre del producto',
product_price: 'Precio del producto',
select_category: 'Selecciona una categoría',
category_title: 'Título de la categoría',
suspicious: 'Sospechoso',
spam: 'Correo basura',
inappropriate: 'Inadecuado',
harassing: 'acosar',
edit_category: 'Editar Categoria',
add_category: 'Añadir Categoría',
need_camera_permission: 'Se necesita permiso para la cámara para continuar',
are_you_sure_dismiss_memeber:
  '¿Está seguro de que desea descartar a este miembro como',
demote: 'Degradar',
no_name: 'Sin Nombre',
dismiss_from: 'Descartar de',
owner: 'Propietario',
ban: 'Prohibición',
are_you_sure_to_ban:
  '¿Estás seguro de que quieres prohibir a este miembro?',
unmute: 'No silenciar',
are_you_sure_want_unmute:
  '¿Estás seguro de que quieres dejar de silenciar a este miembro?',
are_you_sure_want_mute: '¿Seguro que quieres silenciar a este miembro?',
dismiss_from_operator: 'Descartar del operador',
promote_operator: 'Promocionar Operador',
are_you_sure_want_report: '¿Estás seguro de que quieres reportar?',
report_member: 'Reportar miembro',
remove_from: 'Remover de',
remove_from_admin: 'Remover de los administradores',
make_admin: 'Hacer administrador',
admin: 'Administrador',
next: 'Próximo',
invite_user: 'Invitar usuario',
are_not_memeber_of_onesay:
  " no son miembros de one'say. ¿Quieres enviarles una invitación?",
please_select_users: 'Por favor seleccione usuarios',
create_channel: 'Crear canal',
create_group: 'Crear grupo',
create: 'Crear',
invite_members: 'Invitar miembros',
please_enter_channel_name: 'Por favor ingresa el nombre del canal',
please_enter_group_name: 'Por favor ingresa el nombre del grupo',
post: 'Correo',
reel: 'carrete',
create_post: 'Crear publicación',
whats_on_your_mind: 'Qué tienes en mente',
upload: 'Subir',
reels_updated_successfully: 'Carretes actualizados con éxito',
please_enter_content: 'Por favor ingrese el contenido',
reels_added_successfully: 'Carretes agregados con éxito',
error_while_uploading_reels: 'Error al cargar carretes',
content_should_be_at_least:
  'El contenido debe tener al menos 3 caracteres.',
couldnt_reach_server:
  "Couldn't reach server. Check your internet connection",
to_call_allow_buzzmi_access:
  'Para llamar, permita que Buzzmi acceda a su cámara y micrófono',
to_answer_allow_buzzmi_access:
  'Para responder, permita que Buzzmi acceda a su cámara y micrófono',
you_need_grant_storage_access:
  'Debe otorgar permisos de acceso al almacenamiento.',
permissions_for_record_audio: 'Permisos para grabar audio',
give_permission_record_audio:
  'Dar permiso a su dispositivo para grabar audio',
You_need_grant_microphone: 'Debe otorgar permisos de acceso al micrófono.',
},



});
export default Strings;
